INSERT INTO review_class VALUES ('1000', 'iOS Platform');
INSERT INTO review_class VALUES ('1001', 'Global Navigation');
INSERT INTO review_class VALUES ('1002', 'DDA Profile');
INSERT INTO review_class VALUES ('1003', 'PFM');
INSERT INTO review_class VALUES ('1004', 'PFMMPLACE');
INSERT INTO review_class VALUES ('1005', 'PUSH iOS');
INSERT INTO review_class VALUES ('1006', 'DBP.Витрины продаж');
INSERT INTO review_class VALUES ('1007', 'Госуслуги');
INSERT INTO review_class VALUES ('1008', 'iOS Release Engineer');
INSERT INTO review_class VALUES ('1009', 'Мессенджер');
INSERT INTO review_class VALUES ('1010', 'Store-n-Sales');
INSERT INTO review_class VALUES ('1011', 'Integration Platform');
INSERT INTO review_class VALUES ('1012', 'Data Driven App');
INSERT INTO review_class VALUES ('1013', 'Краудфандинг');
INSERT INTO review_class VALUES ('1014', 'DBP.Подарки');
INSERT INTO review_class VALUES ('1015', 'Sberbank ID B2C');
INSERT INTO review_class VALUES ('1016', 'История операций');
INSERT INTO review_class VALUES ('1017', 'Редактируемый профиль клиента');
INSERT INTO review_class VALUES ('1018', 'ЕФС Выписки и справки. Mobile');
INSERT INTO review_class VALUES ('1019', 'ЕФС.Платежи МП');
INSERT INTO review_class VALUES ('1020', 'Платежи. Штрафы');
INSERT INTO review_class VALUES ('1021', 'ПДВ в Digital');
INSERT INTO review_class VALUES ('1022', 'СБОЛ. Классические переводы');
INSERT INTO review_class VALUES ('1023', 'ЕФС.Автоплатежи');
INSERT INTO review_class VALUES ('1024', 'Автопереводы');
INSERT INTO review_class VALUES ('1025', 'Digital Сбербанк Премьер');
INSERT INTO review_class VALUES ('1026', 'Развитие лояльности в МП СБОЛ');
INSERT INTO review_class VALUES ('1027', 'Дебетовые карты в мобильном приложении');
INSERT INTO review_class VALUES ('1028', 'Карта в телефоне');
INSERT INTO review_class VALUES ('1029', 'Digital PIN');
INSERT INTO review_class VALUES ('1030', 'Плановый и досрочный перевыпуск дебетовых карт');
INSERT INTO review_class VALUES ('1031', 'Самозанятые');
INSERT INTO review_class VALUES ('1032', 'Цифровой Кредит');
INSERT INTO review_class VALUES ('1033', 'ВС.МП вклады');
INSERT INTO review_class VALUES ('1034', 'Комиссионные продукты');
INSERT INTO review_class VALUES ('1035', 'PFM Бюджет');
INSERT INTO review_class VALUES ('1036', 'Mobile Online POS (Розничный кредит)');
INSERT INTO review_class VALUES ('1037', 'Текстовый чат');
INSERT INTO review_class VALUES ('1038', '[ЕФС].Кредитные карты.Космонавты (Доп. услуги и сервисы)');
INSERT INTO review_class VALUES ('1039', 'ЕФС. Брокеридж. Мобайл');
INSERT INTO review_class VALUES ('1040', '[ЕФС] Б.УБ.СБОЛ.Баллонг');
INSERT INTO review_class VALUES ('1041', 'ЕФС. Страхование');
INSERT INTO review_class VALUES ('1042', 'Телеком');